import Head from 'next/head';

import {
  Hero,
  Stats,
  Billing,
  Business,
  CardDeal,
  Clients,
  CTA,
  Testimonials,
} from '../components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bank App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main>
        <Hero />
        <Stats />
        <Business />
        <Billing />
        <CardDeal />
        <Testimonials />
        <Clients />
        <CTA />
      </main>
    </div>
  );
}
